<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/WCC_Search/v1.0" xmlns:ns0="http://www.stellent.com/Search/" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_consulta_wcc">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/resources/SOA/WSDLs/Search.wsdl"/>
            <oracle-xsl-mapper:rootElement name="QuickSearchResponse" namespace="http://www.stellent.com/Search/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpel_consulta_wcc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="output" namespace="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/WCC_Search/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI APR 03 10:50:49 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:output>
         <xsl:if test="count (/ns0:QuickSearchResponse/ns0:QuickSearchResult/ns0:SearchResults ) > 0">
            <xsl:for-each select="/ns0:QuickSearchResponse/ns0:QuickSearchResult/ns0:SearchResults">
               <tns:searchResults>
                  <tns:dID>
                     <xsl:value-of select="ns0:dID"/>
                  </tns:dID>
                  <tns:revision>
                     <xsl:value-of select="ns0:dRevisionID"/>
                  </tns:revision>
                  <tns:dDocName>
                     <xsl:value-of select="ns0:dDocName"/>
                  </tns:dDocName>
                  <tns:titulo>
                     <xsl:value-of select="ns0:dDocTitle"/>
                  </tns:titulo>
                  <tns:tipo>
                     <xsl:value-of select="ns0:dDocType"/>
                  </tns:tipo>
                  <tns:autor>
                     <xsl:value-of select="ns0:dDocAuthor"/>
                  </tns:autor>
                  <tns:grupoSeguridad>
                     <xsl:value-of select="ns0:dSecurityGroup"/>
                  </tns:grupoSeguridad>
                  <tns:cuenta>
                     <xsl:value-of select="ns0:dDocAccount"/>
                  </tns:cuenta>
                  <tns:extension>
                     <xsl:value-of select="ns0:dExtension"/>
                  </tns:extension>
                  <tns:extensionWeb>
                     <xsl:value-of select="ns0:dWebExtension"/>
                  </tns:extensionWeb>
                  <tns:revision>
                     <xsl:value-of select="ns0:dRevLabel"/>
                  </tns:revision>
                  <tns:fechaCreacion>
                     <xsl:value-of select="ns0:dInDate"/>
                  </tns:fechaCreacion>
                  <tns:formato>
                     <xsl:value-of select="ns0:dFormat"/>
                  </tns:formato>
                  <tns:nombreOriginal>
                     <xsl:value-of select="ns0:dOriginalName"/>
                  </tns:nombreOriginal>
                  <tns:url>
                     <xsl:value-of select="ns0:url"/>
                  </tns:url>
                  <xsl:if test="count (ns0:CustomDocMetaData/ns0:property ) > 0">
                     <xsl:for-each select="ns0:CustomDocMetaData/ns0:property">
                        <tns:customDocMetaData>
                           <tns:name>
                              <xsl:value-of select="ns0:name"/>
                           </tns:name>
                           <tns:value>
                              <xsl:value-of select="ns0:value"/>
                           </tns:value>
                        </tns:customDocMetaData>
                     </xsl:for-each>
                  </xsl:if>
               </tns:searchResults>
            </xsl:for-each>
         </xsl:if>
      </tns:output>
   </xsl:template>
</xsl:stylesheet>
